package com.example.model

/**
 * Represents the actor sending the message.
 */
enum class Sender {
    USER,
    AI
}

/**
 * Represents an interactive widget, dashboard, or game generated by the LLM.
 */
data class Artifact(
    val id: String,
    val title: String,
    val type: String, // "game", "dashboard", "utility"
    val code: String, // HTML/JS/CSS sandbox code
    val iconName: String, // Material symbol icon name representation
    val description: String,
    val timestamp: Long = System.currentTimeMillis()
)

/**
 * Represents a single message in a chat history, which can contain text,
 * live GGUF diagnostic logs, or a dynamic executable artifact.
 */
data class ChatMessage(
    val id: String,
    val sender: Sender,
    val text: String,
    val timestamp: Long = System.currentTimeMillis(),
    val isArtifactLoading: Boolean = false,
    val artifact: Artifact? = null,
    val ggufInferenceLogs: String? = null
)

/**
 * Represents a complete chat session.
 */
data class ChatSession(
    val id: String,
    val title: String,
    val timestamp: Long = System.currentTimeMillis()
)
